version: "3.9"
services:
    web:
      build: .

      volumes:
        - .:/app

      ports:
        - "9000:9000"

      image: questoes:app

      container_name: sistema_container

      restart: always

      command: python3 manage.py runserver 0.0.0.0:9000
      
                    
volumes:
  db_data: {}