version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app  # Monta toda a pasta do projeto
    ports:
      - "8000:8000"
    container_name: sistema_container
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static  # Aqui os arquivos coletados estarão
      - ./midias_users:/app/midias_users  # Pasta de mídias
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
