version: "3.9"
services:
    web:
      build: .

      volumes:
        - .:/app

      ports:
        - "8000:8000"

      image: questoes:app

      container_name: sistema_container

      restart: always

      command: python manage.py runserver 0.0.0.0:8000
      
                    
volumes:
  db_data: {}