# Generated by Django 3.2 on 2021-04-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('alternativas_correta', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'Certo'), (6, 'Errado')])),
                ('disponivel', models.BooleanField(default=False)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.banca')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.materia')),
            ],
        ),
    ]
