# Generated by Django 3.2 on 2021-05-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas_correta',
            field=models.IntegerField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Certo', 'Certo'), ('Errado', 'Errado')]),
        ),
    ]
