# Generated by Django 3.2 on 2021-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_alter_pergunta_alternativas_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas_correta',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'Certo'), (6, 'Errado')]),
        ),
    ]
