# Generated by Django 3.2 on 2021-05-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_alter_pergunta_alternativas_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
