# Generated by Django 3.2 on 2021-05-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0007_auto_20210509_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='respondida',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='usuario',
        ),
    ]
