# Generated by Django 3.2 on 2021-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0008_auto_20210509_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
