# Generated by Django 3.2 on 2021-05-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0010_rename_pergunta_respondida_resposta_respondida'),
        ('perguntas', '0009_pergunta_respondida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='respondida',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respostas.resposta'),
        ),
    ]
