# Generated by Django 3.2 on 2021-05-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0010_auto_20210512_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='resposta_usuario',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
