# Generated by Django 3.2 on 2021-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0012_remove_pergunta_respondida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='alternativas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
