# Generated by Django 3.2 on 2021-06-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0018_alter_pergunta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas_correta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Certo', 'Certo'), ('Errado', 'Errado')], max_length=10),
        ),
    ]
