# Generated by Django 3.2 on 2021-06-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumeruser',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costumeruser',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotoPerfil'),
        ),
    ]
