# Generated by Django 5.1.1 on 2025-03-26 23:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_costumeruser_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumeruser',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
