# Generated by Django 3.2 on 2021-05-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_alter_pergunta_alternativas_correta'),
        ('respostas', '0002_auto_20210502_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta'),
        ),
    ]
