# Generated by Django 3.2 on 2021-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0003_alter_resposta_resposta_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_certa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_errada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
