# Generated by Django 3.2 on 2021-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0004_auto_20210502_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta_certa',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_errada',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
