# Generated by Django 3.2 on 2021-05-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0005_auto_20210503_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
