# Generated by Django 3.2 on 2021-05-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0006_resposta_respondida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='resposta_certa',
            new_name='resposta_usuario',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resposta_errada',
        ),
    ]
