# Generated by Django 3.2 on 2021-05-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0007_auto_20210507_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='respondida',
        ),
    ]
