# Generated by Django 3.2 on 2021-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0008_remove_resposta_respondida'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pergunta_respondida',
            field=models.BooleanField(default=False),
        ),
    ]
