# Generated by Django 3.2 on 2021-05-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0009_resposta_pergunta_respondida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='pergunta_respondida',
            new_name='respondida',
        ),
    ]
