# Generated by Django 3.2 on 2021-05-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('respostas', '0010_rename_pergunta_respondida_resposta_respondida'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='banca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categorias.banca'),
            preserve_default=False,
        ),
    ]
