# Generated by Django 3.2 on 2021-05-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0011_resposta_banca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='banca',
        ),
    ]
