# Generated by Django 3.2 on 2021-05-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0014_alter_resposta_banca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='banca',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
